# Generated by Django 3.0.10 on 2020-10-02 13:51

from django.db import migrations


def create_interval_schedule(apps, schema_editor):
    interval_schedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    interval_obj_list = []
    for num in range(1, 25):
        obj = interval_schedule(every=num, period="hours")
        interval_obj_list.append(obj)
    interval_schedule.objects.bulk_create(interval_obj_list)


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "__latest__")

    ]

    operations = [
        migrations.RunPython(create_interval_schedule)
    ]
